import type { Product } from './types'

export const PRODUCTS: Product[] = [
  {
    id: 'geometric-vase-01',
    name: 'Bình Hoa Hình Học Gợn Sóng',
    tagline: 'Các mặt xếp lớp chính xác bắt từng tia sáng.',
    description:
      'Điểm nhấn nổi bật với các mặt hình học xếp lớp theo dòng chảy. In bằng PLA mịn để hoàn thiện sạch bóng, bình hoa này cắm được hoa tươi hoặc hoa khô và ngay lập tức trở thành tâm điểm trên kệ hay bàn của bạn.',
    price: 1899,
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
      'https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=600&q=80',
      'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&q=80',
    ],
    modelUrl: '/models/vase.glb',
    category: 'home-decor',
    materials: ['PLA', 'PETG'],
    printerCompatibility: ['X1C', 'P1S', 'A1', 'All'],
    layerHeight: 0.2,
    printTime: '~4h 30m',
    supportRequired: false,
    featured: true,
    inStock: true,
    rating: 4.8,
    reviewCount: 124,
    tags: ['vase', 'geometric', 'home decor', 'minimalist'],
  },
  {
    id: 'hex-shelf-01',
    name: 'Kệ Tường Lục Giác',
    tagline: 'Lưu trữ tổ ong mô-đun, sẵn sàng gắn tường.',
    description:
      'Gắn riêng lẻ hoặc kết hợp nhiều chiếc để tạo bức tường kệ tổ ong. Mỗi kệ chịu được tới 1,5 kg. Được giao ở dạng các tấm in phẳng có thể ghép lại với nhau — không cần keo.',
    price: 2499,
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80',
      'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600&q=80',
    ],
    category: 'home-decor',
    materials: ['PLA', 'PETG', 'ABS'],
    printerCompatibility: ['X1C', 'P1S', 'P1P', 'All'],
    layerHeight: 0.2,
    printTime: '~6h 15m',
    supportRequired: false,
    featured: false,
    inStock: true,
    rating: 4.6,
    reviewCount: 87,
    tags: ['shelf', 'hexagon', 'wall mount', 'storage'],
  },
  {
    id: 'planter-geometric',
    name: 'Chậu Cây Hình Học',
    tagline: 'Thiết kế đa giác thấp gặp gỡ cây trồng dễ chăm.',
    description:
      'Chậu đa diện với lỗ thoát nước và khay di động. Thiết kế đa giác thấp kết hợp hoàn hảo với xương rồng, cây mọng nước hay thảo mộc nhỏ. In kín nước bằng PETG.',
    price: 1599,
    images: [
      'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&q=80',
      'https://images.unsplash.com/photo-1545241047-6083a3684587?w=600&q=80',
    ],
    category: 'home-decor',
    materials: ['PETG', 'PLA'],
    printerCompatibility: ['A1', 'A1 Mini', 'P1S', 'All'],
    layerHeight: 0.2,
    printTime: '~3h 45m',
    supportRequired: false,
    featured: false,
    inStock: true,
    rating: 4.7,
    reviewCount: 63,
    tags: ['planter', 'succulent', 'geometric', 'garden'],
  },
  {
    id: 'dragon-articulated-01',
    name: 'Rồng Cử Động',
    tagline: 'Mỗi khớp đều cử động. In trong một lần.',
    description:
      'Rồng cử động hoàn toàn, in không cần đế đỡ hay lắp ráp — mỗi khớp và đốt sống đều cử động ngay khi lấy khỏi bàn in. Một tác phẩm kỹ thuật mà cả trẻ em lẫn nhà sưu tầm đều yêu thích.',
    price: 1499,
    images: [
      'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600&q=80',
      'https://images.unsplash.com/photo-1578632292335-df3abbb0d586?w=600&q=80',
    ],
    modelUrl: '/models/dragon.glb',
    category: 'toys',
    materials: ['PLA', 'PETG'],
    printerCompatibility: ['X1C', 'P1S', 'A1', 'P1P', 'All'],
    layerHeight: 0.15,
    printTime: '~8h 20m',
    supportRequired: false,
    featured: true,
    inStock: true,
    rating: 4.9,
    reviewCount: 218,
    tags: ['dragon', 'articulated', 'fidget', 'collectible'],
  },
  {
    id: 'rocket-fidget-01',
    name: 'Fidget Spinner Tên Lửa',
    tagline: 'Vòng bi mượt mà. Phong cách vũ trụ.',
    description:
      'Fidget spinner ba cánh hình tên lửa với vòng bi 608 tích hợp. Cân bằng để quay lâu, im lặng. Đồ chơi bàn làm việc tuyệt vời để tập trung và giảm căng thẳng.',
    price: 799,
    images: [
      'https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=600&q=80',
      'https://images.unsplash.com/photo-1555487505-8603a1a69755?w=600&q=80',
    ],
    category: 'toys',
    materials: ['PLA', 'PETG', 'ABS'],
    printerCompatibility: ['A1 Mini', 'A1', 'P1S', 'All'],
    layerHeight: 0.2,
    printTime: '~1h 45m',
    supportRequired: false,
    featured: false,
    inStock: true,
    rating: 4.4,
    reviewCount: 95,
    tags: ['fidget', 'spinner', 'rocket', 'toy'],
  },
  {
    id: 'gear-fidget-01',
    name: 'Fidget Bánh Răng Hành Tinh',
    tagline: 'Sáu bánh răng quay đồng bộ hoàn hảo.',
    description:
      'Hệ thống bánh răng hành tinh mê hoặc, trong đó bánh răng mặt trời ở giữa dẫn động sáu bánh răng hành tinh trên vành. Thú vị khi quay, có tính giáo dục khi giải thích. Không cần lắp ráp.',
    price: 1199,
    images: [
      'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&q=80',
      'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=600&q=80',
    ],
    category: 'toys',
    materials: ['PLA', 'PETG'],
    printerCompatibility: ['X1C', 'P1S', 'A1', 'All'],
    layerHeight: 0.15,
    printTime: '~5h 10m',
    supportRequired: false,
    featured: false,
    inStock: true,
    rating: 4.7,
    reviewCount: 142,
    tags: ['gear', 'planetary', 'fidget', 'mechanical'],
  },
  {
    id: 'cable-clip-pack',
    name: 'Bộ Kẹp Dây Cáp 6 Cái',
    tagline: 'Dán một lần, gọn gàng mãi mãi.',
    description:
      'Sáu kẹp dây cáp có băng dính phù hợp với USB-C, HDMI và cáp nguồn. Gắn trên mép bàn hoặc cánh tay màn hình. In bằng TPU mềm dẻo để cáp bấm vào và ra dễ dàng.',
    price: 999,
    images: [
      'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    ],
    category: 'tools',
    materials: ['TPU', 'PLA'],
    printerCompatibility: ['A1', 'A1 Mini', 'P1S', 'P1P', 'X1C', 'All'],
    layerHeight: 0.2,
    printTime: '~2h 00m',
    supportRequired: false,
    featured: false,
    inStock: true,
    rating: 4.5,
    reviewCount: 77,
    tags: ['cable', 'organizer', 'desk', 'office'],
  },
  {
    id: 'wrench-holder-01',
    name: 'Giá Đỡ Cờ Lê Từ Tính',
    tagline: 'Mỗi chiếc cờ lê đều có chỗ, luôn luôn.',
    description:
      'Giá đỡ cờ lê gắn tường với các khe nam châm neodymium (nam châm bán riêng). Chứa được tới 12 chiếc cờ lê. In bằng PETG bền chắc với lỗ gắn tường được gia cố.',
    price: 1799,
    images: [
      'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600&q=80',
      'https://images.unsplash.com/photo-1581244277943-fe4a9c777189?w=600&q=80',
    ],
    category: 'tools',
    materials: ['PETG', 'ABS'],
    printerCompatibility: ['X1C', 'P1S', 'P1P', 'All'],
    layerHeight: 0.25,
    printTime: '~5h 30m',
    supportRequired: true,
    featured: false,
    inStock: true,
    rating: 4.6,
    reviewCount: 54,
    tags: ['wrench', 'tool storage', 'garage', 'workshop'],
  },
  {
    id: 'voronoi-lamp-01',
    name: 'Đèn Bàn Voronoi',
    tagline: 'Nghệ thuật bóng tối được tạo bởi toán học.',
    description:
      'Chao đèn tessellation Voronoi chiếu các mẫu ô phức tạp khắp căn phòng. Tương thích với bất kỳ đui đèn E26 nào (không kèm). In bằng PETG trong suốt để tạo ánh sáng ấm áp.',
    price: 3499,
    images: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80',
      'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=600&q=80',
    ],
    modelUrl: '/models/lamp.glb',
    category: 'art',
    materials: ['PETG', 'PLA'],
    printerCompatibility: ['X1C', 'P1S', 'All'],
    layerHeight: 0.15,
    printTime: '~14h 00m',
    supportRequired: false,
    featured: true,
    inStock: true,
    rating: 4.9,
    reviewCount: 186,
    tags: ['lamp', 'voronoi', 'lighting', 'art'],
  },
  {
    id: 'wave-wall-art',
    name: 'Tranh Tường Địa Hình Sóng',
    tagline: 'Đường đồng mức địa hình, sẵn sàng trưng bày.',
    description:
      'Bảng sóng địa hình nhiều lớp lấy cảm hứng từ bản đồ đáy biển. Mỗi đường đồng mức là một bản in riêng biệt màu tương phản, xếp chồng và dán lại để tạo hiệu ứng nổi 3D. Giao hàng phẳng để dễ đóng khung.',
    price: 2199,
    images: [
      'https://images.unsplash.com/photo-1578321272176-b7bbc0679853?w=600&q=80',
      'https://images.unsplash.com/photo-1549490349-8643362247b5?w=600&q=80',
    ],
    category: 'art',
    materials: ['PLA', 'PETG'],
    printerCompatibility: ['A1', 'P1S', 'X1C', 'All'],
    layerHeight: 0.2,
    printTime: '~7h 45m',
    supportRequired: false,
    featured: false,
    inStock: true,
    rating: 4.7,
    reviewCount: 103,
    tags: ['wall art', 'topographic', 'wave', 'abstract'],
  },
  {
    id: 'pi-keychain',
    name: 'Móc Khóa Số Pi',
    tagline: 'Mang vô cực trong túi bạn.',
    description:
      'Móc khóa mỏng khắc 50 chữ số đầu tiên của pi. In bằng PLA cứng với lớp hoàn thiện bóng. Món quà dành cho người yêu toán học, vừa túi bất kỳ ai.',
    price: 599,
    images: [
      'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=600&q=80',
      'https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=600&q=80',
    ],
    category: 'art',
    materials: ['PLA'],
    printerCompatibility: ['A1 Mini', 'A1', 'P1S', 'All'],
    layerHeight: 0.1,
    printTime: '~0h 45m',
    supportRequired: false,
    featured: false,
    inStock: true,
    rating: 4.3,
    reviewCount: 212,
    tags: ['keychain', 'pi', 'math', 'gift'],
  },
  {
    id: 'gopro-mount-01',
    name: 'Giá Gắn GoPro Tay Lái',
    tagline: 'Khóa GoPro vào bất kỳ tay lái nào trong vài giây.',
    description:
      'Giá gắn tay lái tương thích GoPro phổ thông cho ghi đông 22–35 mm. In bằng ASA chống UV và nhiệt. Đã thử nghiệm ở độ rung 80 km/h không bị rơ. Kèm đai ốc khóa in sẵn.',
    price: 1299,
    images: [
      'https://images.unsplash.com/photo-1502744688674-c619d1586c9e?w=600&q=80',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    ],
    modelUrl: '/models/mount.glb',
    category: 'functional-parts',
    materials: ['ASA', 'ABS', 'PETG'],
    printerCompatibility: ['X1C', 'P1S', 'P1P', 'All'],
    layerHeight: 0.2,
    printTime: '~3h 15m',
    supportRequired: true,
    featured: true,
    inStock: true,
    rating: 4.8,
    reviewCount: 167,
    tags: ['gopro', 'mount', 'cycling', 'outdoor'],
  },
  {
    id: 'cable-routing-desk',
    name: 'Hệ Thống Quản Lý Cáp Bàn Làm Việc',
    tagline: 'Quản lý cáp gầm bàn, đã được giải quyết.',
    description:
      'Khay cáp gầm bàn mô-đun với các kênh kẹp snap-in. Gắn bằng băng dính hai mặt hoặc vít. Giữ ổ cắm điện, bộ lọc điện và bó cáp gọn gàng ngoài tầm nhìn.',
    price: 2099,
    images: [
      'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80',
    ],
    category: 'functional-parts',
    materials: ['PLA', 'PETG'],
    printerCompatibility: ['A1', 'P1S', 'X1C', 'All'],
    layerHeight: 0.25,
    printTime: '~9h 00m',
    supportRequired: false,
    featured: false,
    inStock: true,
    rating: 4.6,
    reviewCount: 89,
    tags: ['cable management', 'desk', 'office', 'organizer'],
  },
  {
    id: 'phone-stand-01',
    name: 'Giá Đỡ Điện Thoại Điều Chỉnh',
    tagline: 'Mọi góc độ, mọi bàn, mọi điện thoại.',
    description:
      'Giá đỡ điện thoại gập được với bản lề ma sát giữ bất kỳ góc nào từ 20° đến 80°. Dùng với điện thoại rộng tới 85 mm kể cả ốp lưng. Gập phẳng để mang đi.',
    price: 1099,
    images: [
      'https://images.unsplash.com/photo-1556656793-08538906a9f8?w=600&q=80',
      'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&q=80',
    ],
    category: 'functional-parts',
    materials: ['PETG', 'PLA', 'ABS'],
    printerCompatibility: ['A1 Mini', 'A1', 'P1S', 'P1P', 'X1C', 'All'],
    layerHeight: 0.2,
    printTime: '~2h 30m',
    supportRequired: false,
    featured: false,
    inStock: true,
    rating: 4.5,
    reviewCount: 134,
    tags: ['phone stand', 'desk', 'travel', 'adjustable'],
  },
]

export const CATEGORIES = [
  { id: 'home-decor' as const, label: 'Trang trí nội thất', icon: 'Home' },
  { id: 'toys' as const, label: 'Đồ chơi & Sưu tập', icon: 'Gamepad2' },
  { id: 'tools' as const, label: 'Công cụ & Lưu trữ', icon: 'Wrench' },
  { id: 'art' as const, label: 'Nghệ thuật & Điêu khắc', icon: 'Palette' },
  { id: 'functional-parts' as const, label: 'Linh kiện chức năng', icon: 'Settings2' },
]
