import type { Product } from './types'

export const PRODUCTS: Product[] = [
  {
    id: 'geometric-vase-01',
    name: 'Geometric Ripple Vase',
    tagline: 'Precision-layered facets that catch every light.',
    description:
      'A striking centerpiece with cascading geometric facets. Printed in smooth PLA for a clean finish, this vase holds fresh or dried flowers and makes an instant conversation piece on any shelf or table.',
    price: 1899,
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
      'https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=600&q=80',
      'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&q=80',
    ],
    modelUrl: '/models/vase.glb',
    category: 'home-decor',
    materials: ['PLA', 'PETG'],
    printerCompatibility: ['X1C', 'P1S', 'A1', 'All'],
    layerHeight: 0.2,
    printTime: '~4h 30m',
    supportRequired: false,
    featured: true,
    inStock: true,
    rating: 4.8,
    reviewCount: 124,
    tags: ['vase', 'geometric', 'home decor', 'minimalist'],
  },
  {
    id: 'hex-shelf-01',
    name: 'Hexagonal Wall Shelf',
    tagline: 'Modular honeycomb storage, wall-ready.',
    description:
      'Mount individually or cluster multiple units for a honeycomb display wall. Each shelf can hold up to 1.5 kg. Ships as flat-printed panels that snap together — no glue required.',
    price: 2499,
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80',
      'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600&q=80',
    ],
    category: 'home-decor',
    materials: ['PLA', 'PETG', 'ABS'],
    printerCompatibility: ['X1C', 'P1S', 'P1P', 'All'],
    layerHeight: 0.2,
    printTime: '~6h 15m',
    supportRequired: false,
    featured: false,
    inStock: true,
    rating: 4.6,
    reviewCount: 87,
    tags: ['shelf', 'hexagon', 'wall mount', 'storage'],
  },
  {
    id: 'planter-geometric',
    name: 'Geometric Succulent Planter',
    tagline: 'Low-poly design meets low-maintenance plants.',
    description:
      'A faceted planter with a drainage hole and removable tray. The low-poly aesthetic pairs perfectly with succulents, cacti, or small herbs. Printed watertight in PETG.',
    price: 1599,
    images: [
      'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&q=80',
      'https://images.unsplash.com/photo-1545241047-6083a3684587?w=600&q=80',
    ],
    category: 'home-decor',
    materials: ['PETG', 'PLA'],
    printerCompatibility: ['A1', 'A1 Mini', 'P1S', 'All'],
    layerHeight: 0.2,
    printTime: '~3h 45m',
    supportRequired: false,
    featured: false,
    inStock: true,
    rating: 4.7,
    reviewCount: 63,
    tags: ['planter', 'succulent', 'geometric', 'garden'],
  },
  {
    id: 'dragon-articulated-01',
    name: 'Articulated Dragon',
    tagline: 'Every joint moves. Printed in one piece.',
    description:
      'A fully articulated dragon printed without supports or assembly — every joint and spine segment moves right off the build plate. A technical showpiece that kids and collectors love equally.',
    price: 1499,
    images: [
      'https://images.unsplash.com/photo-1612099197634-b2e1b1ea3edc?w=600&q=80',
      'https://images.unsplash.com/photo-1578632292335-df3abbb0d586?w=600&q=80',
    ],
    modelUrl: '/models/dragon.glb',
    category: 'toys',
    materials: ['PLA', 'PETG'],
    printerCompatibility: ['X1C', 'P1S', 'A1', 'P1P', 'All'],
    layerHeight: 0.15,
    printTime: '~8h 20m',
    supportRequired: false,
    featured: true,
    inStock: true,
    rating: 4.9,
    reviewCount: 218,
    tags: ['dragon', 'articulated', 'fidget', 'collectible'],
  },
  {
    id: 'rocket-fidget-01',
    name: 'Rocket Fidget Spinner',
    tagline: 'Smooth bearings. Space-age style.',
    description:
      'A three-blade fidget spinner shaped like a rocket with integrated 608 bearings. Balanced for a long, silent spin. Great desk toy for focus and stress relief.',
    price: 799,
    images: [
      'https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=600&q=80',
      'https://images.unsplash.com/photo-1555487505-8603a1a69755?w=600&q=80',
    ],
    category: 'toys',
    materials: ['PLA', 'PETG', 'ABS'],
    printerCompatibility: ['A1 Mini', 'A1', 'P1S', 'All'],
    layerHeight: 0.2,
    printTime: '~1h 45m',
    supportRequired: false,
    featured: false,
    inStock: true,
    rating: 4.4,
    reviewCount: 95,
    tags: ['fidget', 'spinner', 'rocket', 'toy'],
  },
  {
    id: 'gear-fidget-01',
    name: 'Planetary Gear Fidget',
    tagline: 'Six gears spin in perfect sync.',
    description:
      'A mesmerizing planetary gear system where a central sun gear drives six planet gears in a ring. Satisfying to spin, educational to explain. No assembly needed.',
    price: 1199,
    images: [
      'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&q=80',
      'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=600&q=80',
    ],
    category: 'toys',
    materials: ['PLA', 'PETG'],
    printerCompatibility: ['X1C', 'P1S', 'A1', 'All'],
    layerHeight: 0.15,
    printTime: '~5h 10m',
    supportRequired: false,
    featured: false,
    inStock: true,
    rating: 4.7,
    reviewCount: 142,
    tags: ['gear', 'planetary', 'fidget', 'mechanical'],
  },
  {
    id: 'cable-clip-pack',
    name: 'Cable Clip Organizer 6-Pack',
    tagline: 'Stick once, stay tidy forever.',
    description:
      'Six adhesive-backed cable clips sized for USB-C, HDMI, and power cables. Mount on your desk edge or monitor arm. Printed in flexible TPU so cables click in and out without force.',
    price: 999,
    images: [
      'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    ],
    category: 'tools',
    materials: ['TPU', 'PLA'],
    printerCompatibility: ['A1', 'A1 Mini', 'P1S', 'P1P', 'X1C', 'All'],
    layerHeight: 0.2,
    printTime: '~2h 00m',
    supportRequired: false,
    featured: false,
    inStock: true,
    rating: 4.5,
    reviewCount: 77,
    tags: ['cable', 'organizer', 'desk', 'office'],
  },
  {
    id: 'wrench-holder-01',
    name: 'Magnetic Wrench Holder',
    tagline: 'Every wrench in its place, always.',
    description:
      'A wall-mounted wrench rack with embedded neodymium magnet slots (magnets sold separately). Holds up to 12 combination wrenches. Printed in durable PETG with reinforced mounting holes.',
    price: 1799,
    images: [
      'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600&q=80',
      'https://images.unsplash.com/photo-1581244277943-fe4a9c777189?w=600&q=80',
    ],
    category: 'tools',
    materials: ['PETG', 'ABS'],
    printerCompatibility: ['X1C', 'P1S', 'P1P', 'All'],
    layerHeight: 0.25,
    printTime: '~5h 30m',
    supportRequired: true,
    featured: false,
    inStock: true,
    rating: 4.6,
    reviewCount: 54,
    tags: ['wrench', 'tool storage', 'garage', 'workshop'],
  },
  {
    id: 'voronoi-lamp-01',
    name: 'Voronoi Table Lamp',
    tagline: 'Math-generated shadow art for your desk.',
    description:
      'A Voronoi-tessellated lamp shade that casts intricate cell patterns across the room. Compatible with any E26 bulb socket (not included). Printed in translucent PETG for a warm glow.',
    price: 3499,
    images: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80',
      'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=600&q=80',
    ],
    modelUrl: '/models/lamp.glb',
    category: 'art',
    materials: ['PETG', 'PLA'],
    printerCompatibility: ['X1C', 'P1S', 'All'],
    layerHeight: 0.15,
    printTime: '~14h 00m',
    supportRequired: false,
    featured: true,
    inStock: true,
    rating: 4.9,
    reviewCount: 186,
    tags: ['lamp', 'voronoi', 'lighting', 'art'],
  },
  {
    id: 'wave-wall-art',
    name: 'Wave Topology Wall Art',
    tagline: 'Topographic contours, gallery-ready.',
    description:
      'A multi-layer topographic wave panel inspired by ocean bathymetry maps. Each contour line is a separate print in contrasting colors, stacked and glued for a 3D relief effect. Ships flat for easy framing.',
    price: 2199,
    images: [
      'https://images.unsplash.com/photo-1578321272176-b7bbc0679853?w=600&q=80',
      'https://images.unsplash.com/photo-1549490349-8643362247b5?w=600&q=80',
    ],
    category: 'art',
    materials: ['PLA', 'PETG'],
    printerCompatibility: ['A1', 'P1S', 'X1C', 'All'],
    layerHeight: 0.2,
    printTime: '~7h 45m',
    supportRequired: false,
    featured: false,
    inStock: true,
    rating: 4.7,
    reviewCount: 103,
    tags: ['wall art', 'topographic', 'wave', 'abstract'],
  },
  {
    id: 'pi-keychain',
    name: 'Pi Constant Keychain',
    tagline: 'Carry infinity in your pocket.',
    description:
      'A slim keychain engraved with the first 50 digits of pi. Printed in rigid PLA with a polished finish. A nerdy gift that fits in any pocket.',
    price: 599,
    images: [
      'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=600&q=80',
      'https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=600&q=80',
    ],
    category: 'art',
    materials: ['PLA'],
    printerCompatibility: ['A1 Mini', 'A1', 'P1S', 'All'],
    layerHeight: 0.1,
    printTime: '~0h 45m',
    supportRequired: false,
    featured: false,
    inStock: true,
    rating: 4.3,
    reviewCount: 212,
    tags: ['keychain', 'pi', 'math', 'gift'],
  },
  {
    id: 'gopro-mount-01',
    name: 'GoPro Handlebar Mount',
    tagline: 'Lock your GoPro to any handlebar in seconds.',
    description:
      'A universal GoPro-compatible handlebar mount that fits 22–35 mm bars. Printed in ASA for UV and heat resistance. Tested at 80 km/h vibration without play. Includes printed locking nut.',
    price: 1299,
    images: [
      'https://images.unsplash.com/photo-1609341687-7c16b1e0e41b?w=600&q=80',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    ],
    modelUrl: '/models/mount.glb',
    category: 'functional-parts',
    materials: ['ASA', 'ABS', 'PETG'],
    printerCompatibility: ['X1C', 'P1S', 'P1P', 'All'],
    layerHeight: 0.2,
    printTime: '~3h 15m',
    supportRequired: true,
    featured: true,
    inStock: true,
    rating: 4.8,
    reviewCount: 167,
    tags: ['gopro', 'mount', 'cycling', 'outdoor'],
  },
  {
    id: 'cable-routing-desk',
    name: 'Desk Cable Routing System',
    tagline: 'Under-desk cable management, finally solved.',
    description:
      'A modular under-desk cable tray with snap-in clip channels. Mounts with double-sided tape or screws. Holds power strips, surge protectors, and cable bundles out of sight.',
    price: 2099,
    images: [
      'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80',
    ],
    category: 'functional-parts',
    materials: ['PLA', 'PETG'],
    printerCompatibility: ['A1', 'P1S', 'X1C', 'All'],
    layerHeight: 0.25,
    printTime: '~9h 00m',
    supportRequired: false,
    featured: false,
    inStock: true,
    rating: 4.6,
    reviewCount: 89,
    tags: ['cable management', 'desk', 'office', 'organizer'],
  },
  {
    id: 'phone-stand-01',
    name: 'Adjustable Phone Stand',
    tagline: 'Any angle, any desk, any phone.',
    description:
      'A foldable phone stand with a friction-fit hinge that holds any angle from 20° to 80°. Works with phones up to 85 mm wide including cases. Folds flat for travel.',
    price: 1099,
    images: [
      'https://images.unsplash.com/photo-1556656793-08538906a9f8?w=600&q=80',
      'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&q=80',
    ],
    category: 'functional-parts',
    materials: ['PETG', 'PLA', 'ABS'],
    printerCompatibility: ['A1 Mini', 'A1', 'P1S', 'P1P', 'X1C', 'All'],
    layerHeight: 0.2,
    printTime: '~2h 30m',
    supportRequired: false,
    featured: false,
    inStock: true,
    rating: 4.5,
    reviewCount: 134,
    tags: ['phone stand', 'desk', 'travel', 'adjustable'],
  },
]

export const CATEGORIES = [
  { id: 'home-decor' as const, label: 'Home Decor', icon: 'Home' },
  { id: 'toys' as const, label: 'Toys & Collectibles', icon: 'Gamepad2' },
  { id: 'tools' as const, label: 'Tools & Storage', icon: 'Wrench' },
  { id: 'art' as const, label: 'Art & Sculpture', icon: 'Palette' },
  { id: 'functional-parts' as const, label: 'Functional Parts', icon: 'Settings2' },
]
